[package]
name = "teloxide-core"
description = "Core part of the `teloxide` library - telegram bot API client"
version = "0.3.3"
edition = "2018"
authors = [
    "Temirkhan Myrzamadi <hirrolot@gmail.com>",
    "Waffle Lapkin <waffle.lapkin@gmail.com>",
    "p0lunin <dmytro.polunin@gmail.com>",
    "Mishko torop'izhko",
    "Mr-Andersen",
    "Sergey Levitin <selevit@gmail.com>",
    "Rustem B. <bakirov.com@yandex.ru>",
    "Alexey Fedechkin <aleksey-fedechkin@rambler.ru>"
]

license = "MIT"
repository = "https://github.com/teloxide/teloxide-core/"
homepage = "https://github.com/teloxide/teloxide-core/"
documentation = "https://docs.rs/teloxide-core/"
readme = "README.md"

keywords = ["telegram", "bot", "tba"]
categories = ["api-bindings", "asynchronous"]

exclude = [
    ".github/*",
    "netlify.toml",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
tokio = { version = "1.8.0", features = ["fs"] }
tokio-util = "0.6.0"
pin-project = "1.0.3"
bytes = "1.0.0"
reqwest = { version = "0.11.0", features = ["json", "stream", "multipart"], default-features = false }
url = { version = "2", features = ["serde"] }
log = "0.4"

serde = { version = "1.0.114", features = ["derive"] }
serde_json = "1.0.55"
serde_with_macros = "1.4.1"
uuid = { version = "0.8.1", features = ["v4"] } # for attaching input files
 
derive_more = "0.99.9"
mime = "0.3.16"
thiserror = "1.0.20"
once_cell = "1.5.0"
never = "0.1.0"
chrono = "0.4.19"
either = "1.6.1"

vecrem = { version = "0.1", optional = true }
bitflags = { version = "1.2", optional = true }

[dev-dependencies]
pretty_env_logger = "0.4"
termcolor = "1.1.2"

[features]
default = ["native-tls"]

rustls = ["reqwest/rustls-tls"]
native-tls = ["reqwest/native-tls"]

# Features which require nightly compiler.
#
# Currently the only used compiler feature is feature(type_alias_impl_trait)
# which allow implementing `Future`s without boxing.
nightly = []

# Throttling bot adaptor
throttle = ["vecrem"]

# Trace bot adaptor
trace_adaptor = ["bitflags"]

# Erased bot adaptor
erased = []

# CacheMe bot adaptor
cache_me = []

# AutoSend bot adaptor
auto_send = []

full = ["throttle", "trace_adaptor", "erased", "cache_me", "auto_send"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "-Znormalize-docs"]

[[example]]
name = "self_info"
required-features = ["tokio/macros", "tokio/rt-multi-thread", "auto_send"]

[[example]]
name = "erased"
required-features = ["tokio/macros", "tokio/rt-multi-thread", "auto_send", "erased"]
